# Use the official Go image from the Docker Hub
FROM golang:latest

# Copy the server-side files to our /app/rpctest4 directory inside the Docker image
WORKDIR /app/rpctest4
COPY ./rpctest4 .

# Build the server-side application
RUN go build -o main

# Expose port for the application
EXPOSE 8888

# Run the binary program produced by `go build`
CMD ["/app/rpctest4/main"]
